ITI-st24-final-project/mysite/accounts/urls.py
from django.urls import include, path
from accounts.views import (
    AccountCreationForm,
    profile,
    edit_profile,
    all_users,
    search_users,
)

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register", AccountCreationForm.as_view(), name="accounts.register"),
    path("profile", profile, name="accounts.profile"),
    path("profile/update", edit_profile, name="accounts.update"),
    path("users", all_users, name="accounts.users"),
    path("search/", search_users, name="accounts.search"),
]

ITI-st24-final-project/mysite/books/urls.py
from django.urls import path
from books.views import (
    add,
    delete_book,
    update_book,
    borrow_book,
    all_books,
    return_book,
    borrowed_books,
)

urlpatterns = [
    path("", all_books, name="book.all"),
    path("add", add, name="book.add"),
    path("delete/<int:book_id>", delete_book, name="book.delete"),
    path("update/<int:book_id>", update_book, name="book.update"),
    path("borrow/<int:book_id>", borrow_book, name="book.borrow"),
    path("borrowed/", borrowed_books, name="book.borrowed"),
    path("return/<int:book_id>", return_book, name="book.return"),
]

ITI-st24-final-project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path("books/", include("books.urls")),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url="/books/", permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ITI-st24-final-project/mysite/accounts/models.py
from django.db import models

# Create your models here.

ITI-st24-final-project/mysite/books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    image = models.ImageField(upload_to="books/images", null=True)
    borrower = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    return_date = models.DateField(null=True)

    def __str__(self):
        return f"{self.title}"

    @property
    def image_url(self):
        return f"/media/{self.image}"

    @property
    def all_url(self):
        url = reverse("book.all")
        return url

    @property
    def edit_url(self):
        url = reverse("book.update", args=[self.id])
        return url

    @property
    def delete_url(self):
        url = reverse("book.delete", args=[self.id])
        return url

    @property
    def borrow_url(self):
        url = reverse("book.borrow", args=[self.id])
        return url

ITI-st24-final-project/mysite/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

from django import forms


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class CustomUserChangeForm(UserChangeForm):
    password = forms.CharField(
        label="New Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        required=False,
        
    )
    password_confirm = forms.CharField(
        label="Confirm New Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        required=False,
    )

    class Meta:
        model = User
        fields = [
            "username",
            "email",
        ]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password != password_confirm:
            self.add_error("password_confirm", "The two password fields must match.")
        return cleaned_data

ITI-st24-final-project/mysite/books/forms.py
from django import forms
from books.models import Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ["title", "author", "image"]

ITI-st24-final-project/mysite/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from accounts.forms import RegistrationForm
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from accounts.forms import CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash


# Create your views here.
class AccountCreationForm(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = "registration/register.html"
    success_url = "/accounts/login"


@login_required()
def profile(request):
    return render(request, "accounts/profile.html", context={"user": request.user})


@login_required()
def edit_profile(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get("password")
            if password:
                user.set_password(password)
                user.save()
                update_session_auth_hash(request, user)
            else:
                user.save()
            return redirect("accounts.profile")
    else:
        form = CustomUserChangeForm(instance=request.user)

    return render(request, "accounts/edit_profile.html", {"form": form})


@login_required()
def all_users(request):
    users = User.objects.all()
    return render(request, "accounts/users.html", context={"users": users})


@login_required()
def search_users(request):
    if request.method == "POST":
        username = request.POST.get("id")
        users = User.objects.filter(id=username)
        return render(request, "accounts/users.html", context={"users": users})
    return render(request, "accounts/users.html")

ITI-st24-final-project/mysite/books/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from books.models import Book
from books.forms import BookForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
import datetime


@login_required
def all_books(request):
    books = Book.objects.all()
    return render(request, "books/index.html", context={"books": books})


@login_required
def delete_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    book.delete()
    url = reverse("book.all")
    return redirect(url)


@login_required
def update_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)

    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect(book.all_url)
    else:
        form = BookForm(instance=book)

    return render(request, "books/edit.html", {"form": form})


@login_required
def borrow_book(request, book_id):
    book = Book.objects.get(id=book_id)
    book.borrower = request.user
    book.return_date = datetime.date.today() + datetime.timedelta(days=7)
    book.save()
    url = reverse("book.all")
    return redirect(url)


@login_required()
def add(request):
    form = BookForm()

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save()
            return redirect(book.all_url)

    return render(request, "books/add.html", {"form": form})


@login_required()
def borrowed_books(request):
    if request.user.username == "admin":
        books = Book.objects.filter(borrower__isnull=False)
    else:
        books = Book.objects.filter(borrower=request.user)
    return render(request, "books/borrowed.html", context={"books": books})


@login_required()
def return_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    book.return_date = None
    book.borrower = None
    book.save()
    url = reverse("book.borrowed")
    return redirect(url)

ITI-st24-final-project/mysite/books/templates/layouts/base.html
    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">Library Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'book.all' %}">All Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'book.borrowed' %}">Borrowed Books</a>
                </li>
                {% if user.username == "admin" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book.add' %}">Add Book</a>
                    </li>
                    <li class="nav-item"></li>
                        <a class="nav-link" href="{% url 'accounts.users' %}">Students</a>
                    </li>
                {% endif %}
                <li class="nav-item"></li>
                    <a class="nav-link">|</a>
                </li>
                <li class="nav-item"></li>
                    <a class="nav-link" href="{% url 'accounts.profile' %}">Profile</a>
                </li>
                
                <li class="nav-item">
                    <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                        <input type="submit" class="nav-link" value="logout">
                    </form>
                </li>
            {% else %}
                </li>
                    <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                </li>
                    <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts.register' %}">Sign up</a>
                </li>
            {% endif %}
    
        </ul>
        {% if user.username == "admin" %}
            <form class="d-flex" role="search" method="POST" action="{% url 'accounts.search' %}" >{% csrf_token %} 
                <input class="form-control me-2" type="search" placeholder="Search students by ID" aria-label="Search" name="id">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        {% endif %}
    </div>
    </div>
    </nav>

<div class="container">
    <div style="background-color: darkmagenta; color: white;">
        {% block main %}
        {% endblock %}
    </div>
    <div style="background-color: darkolivegreen; color: white;">
        {% block test %}
        {% endblock %}

    </div>
    <div>
        {% block content %}
        {% endblock %}
    </div>

</div>
<footer>
    <p>&copy; Library Management 2024 </p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ITI-st24-final-project/mysite/templates/accounts/edit_profile.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Update Profile</h1>

    <form method="POST" class="form-horizontal">
        {% csrf_token %}
        
        <div class="form-group mb-3">
            <label for="id_username" class="form-label">Username</label>
            <input type="text" name="username" value="{{ form.username.value }}" class="form-control" id="id_username" required>
        </div>

        <div class="form-group mb-3">
            <label for="id_email" class="form-label">Email</label>
            <input type="email" name="email" value="{{ form.email.value }}" class="form-control" id="id_email" required>
        </div>

        <div class="form-group mb-3">
            <label for="id_password" class="form-label">New Password</label>
            <input type="password" name="password" class="form-control" id="id_password" placeholder="Leave blank if you do not want to change your password.">
        </div>

        <div class="form-group mb-3">
            <label for="id_password_confirm" class="form-label">Confirm New Password</label>
            <input type="password" name="password_confirm" class="form-control" id="id_password_confirm">
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock %}

ITI-st24-final-project/mysite/templates/accounts/profile.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <h1>Profile info </h1>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{user.username}}</h5>
      <p class="card-text">
          <b>Email:</b> {{user.email}}<br>
          <b>ID:</b> {{user.id}}
        </p>
      <a href="{% url 'accounts.update'  %}" class="btn btn-primary">Update</a>
    </div>
  </div>

{% endblock  %}

ITI-st24-final-project/mysite/templates/accounts/users.html
{% extends 'layouts/base.html' %}
{% load static  %}
{% block title %} Students {% endblock  %}

{% block content %}

<div>
    {% for std in users %}

        <div class="card" style="width: 18rem; height: inherit; display: inline-block; margin:auto;">
            <div class="card-body">
                <h5 class="card-title">{{std.username}}</h5>
                <p class="card-text">
                    <b>Email:</b> {{std.email}}<br>
                    <b>ID:</b> {{std.id}}
                </p>
                {% if std.book_set.all %}
                    <p class="card-text"><b>Borrowed books:</b></p>
                    {% for book in std.book_set.all %}                    
                        <li class="list-group-item">{{book.title}}</li>
                    {% endfor %}
                {% else %}
                        <p class="card-text">No borrowed books</p>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

ITI-st24-final-project/mysite/templates/books/add.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Add Book {% endblock %}
{% block content %}
<h1 class="mb-4"> Add New Book </h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-group mb-3">
        <label for="id_title" class="form-label">Title</label>
        <input type="text" name="title" class="form-control" id="id_title" value="">
    </div>
    
    <div class="form-group mb-3">
        <label for="id_author" class="form-label">Author</label>
        <input type="text" name="author" class="form-control" id="id_author" value="">
    </div>

    <div class="form-group mb-3">
        <label for="id_image" class="form-label">Image</label>
        <input type="file" name="image" class="form-control-file" id="id_image">
    </div>

    <div class="form-group mt-4">
        <input type="submit" class="btn btn-primary btn-block" value="Add new Book">
    </div>

</form>

{% if form.errors %}
    <div class="alert alert-danger mt-4">
        <ul>
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% endblock %}

ITI-st24-final-project/mysite/templates/books/borrowed.html
{% extends 'layouts/base.html' %}
{% load static  %}
{% block title %} Books {% endblock  %}

{% block content %}

<div>
    {% for book in books %}
    <div class="card border-secondary" style="width: 18rem; display: inline-block; margin:auto;" >
        <img src="{{ book.image_url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{book.title}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{book.author}}</h6>
            {% if book.borrower %}
                <p class="card-text">
                    <b>Borrowed By:</b> {{book.borrower.username}}<br>
                    <b>Return Date:</b> {{book.return_date}}<br>
                </p>
            {% endif %}
            

            {% if not book.borrower and not user.username == "admin" %}
                <a href="{% url 'book.borrow' book.id %}" class="btn btn-primary">Borrow</a>
            {% endif %}

            {% if book.borrower.username == user.username %}
                <a href="{% url 'book.return' book.id %}" class="btn btn-primary">return book</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

ITI-st24-final-project/mysite/templates/books/edit.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Edit book {% endblock %}

{% block content %}
<h1 class="mb-4"> Edit Book </h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-group mb-3">
        <label for="id_title" class="form-label">Title</label>
        <input type="text" name="title" class="form-control" id="id_title" value="{{ form.title.value }}">
    </div>
    
    <div class="form-group mb-3">
        <label for="id_author" class="form-label">Author</label>
        <input type="text" name="author" class="form-control" id="id_author" value="{{ form.author.value }}">
    </div>

    <div class="form-group mb-3">
        <label for="id_image" class="form-label">Image</label>
        <input type="file" name="image" class="form-control-file" id="id_image">
        {% if form.image.value %}
            <small class="form-text">Currently: <a href="{{ form.image.value.url }}" target="_blank">{{ form.image.value }}</a></small>
        {% endif %}
    </div>

    <div class="form-group mt-4">
        <input type="submit" class="btn btn-primary btn-block" value="Save changes">
    </div>

</form>

{% if form.errors %}
    <div class="alert alert-danger mt-4">
        <ul>
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% endblock %}

ITI-st24-final-project/mysite/templates/books/index.html
{% extends 'layouts/base.html' %}
{% load static  %}
{% block title %} Books {% endblock  %}

{% block content %}

<div>
    {% for book in books %}
        <div class="card border-secondary" style="width: 18rem; display: inline-block; margin:auto;" >
            <img src="{{ book.image_url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{book.author}}</h6>
                {% if book.borrower %}
                    <p class="card-text">
                        <b>Borrowed By:</b> {{book.borrower.username}}<br>
                        <b>Return Date:</b> {{book.return_date}}<br>
                    </p>
                {% endif %}
                

                {% if not book.borrower and not user.username == "admin" %}
                    <a href="{% url 'book.borrow' book.id %}" class="btn btn-primary">Borrow</a>
                {% endif %}
                {% if user.username == "admin" %}
                    <a href="{% url 'book.update' book.id %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'book.delete' book.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>

    {% endfor %}
</div>
{% endblock %}